name: cinema_booking
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  path_provider: ^2.1.5
  get_it: ^8.0.3
  dartz: ^0.10.1
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  # for login function
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4
  firebase_auth: ^5.4.2
  scrollable_positioned_list: ^0.3.8

  # suitable with bloc
  # equatable for compares objects (with the same data are considered equal automatically)
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  equatable: ^2.0.7

  # for local database
  sqflite: 2.4.2
  shared_preferences: ^2.5.2

  # support for create model
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0

  # for view support ui 
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0

  # for function watch trailer from youtube
  youtube_player_flutter: ^9.1.1

  # I use dio, because i like dio's api implementation
  # Retrofit It allows define API endpoints using annotations,
  dio: ^5.8.0+1
  retrofit: ^4.4.2

  #format date time and other formats
  intl: ^0.20.2

  # for google map
  google_maps_flutter: ^2.10.0
  google_maps_flutter_web: ^0.5.10

  # 
  go_router: ^14.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # for auto generate
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9

  # object builder state management
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0

  #for icon app
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icons/ticket.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
      generate: true
      image_path: "assets/icons/ticket.png"
    background_color: "#ffffff"
    theme_color: "#000000"
    windows:
      generate: true
      image_path: "assets/icons/ticket.png"
      icon_size: 48 # min:48, max:256, default: 48
    macos:
      generate: true
      image_path: "assets/icons/ticket.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cines/
    - assets/fonts/
    - assets/vectors/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 400
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
