blank_issues_enabled: true
contact_links:
  - name: Cinema Booking Support
    url: https://github.com/ChunhThanhDe/cinema-booking/issues/3#issuecomment-new
    about: Please ask and answer off-topic questions here.
